-- 코드를 입력하세요
SELECT
    U.USER_ID,
    U.NICKNAME,
    SUM(B.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER U
JOIN USED_GOODS_BOARD B
    ON U.USER_ID = B.WRITER_ID
-- 거래 완료된 게시글만 합산
WHERE B.STATUS = 'DONE'
GROUP BY U.USER_ID, U.NICKNAME
-- 그룹별 합계 조건이라 WHERE가 아니라 HAVING - gpt가 알려줬어요..
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_SALES;