-- 코드를 입력하세요
SELECT
    I.NAME,
    I.DATETIME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
-- LEFT JOIN 후 NULL인 애들 = 아직 입양 기록이 없음
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME
LIMIT 3;