-- 코드를 입력하세요
SELECT DISTINCT
    C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단'
  -- 같은 차가 여러 번 대여됐을 수 있으니 DISTINCT 필요
  AND H.START_DATE >= '2022-10-01'
  AND H.START_DATE < '2022-11-01'
ORDER BY C.CAR_ID DESC;