-- 코드를 입력하세요
SELECT
    I.ANIMAL_ID,
    I.ANIMAL_TYPE,
    I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
-- 들어올 땐 Intact, 나갈 땐 중성화된 상태
WHERE I.SEX_UPON_INTAKE LIKE 'Intact%'
  AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%'
       OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY I.ANIMAL_ID;